version: '3.9'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: '*'
      MYSQL_DATABASE: 'mydb'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    volumes:
      - ./database:/docker-entrypoint-initdb.d
