name: '📩 Release Please'
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: 🤝 Release Please
        uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: mysql2-orm
          changelog-path: 'CHANGELOG.md'

      - name: ➕ Actions - Checkout
        uses: actions/checkout@v4
        if: ${{ steps.release.outputs.releases_created }}

      - name: ➕ Actions - Setup NodeJS
        uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.releases_created }}
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: ➕ Cache dependencies
        uses: actions/cache@v4
        if: ${{ steps.release.outputs.releases_created }}
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: 📦 Installing Dependencies
        if: ${{ steps.release.outputs.releases_created }}
        run: npm ci

      - name: 🚀 Building MySQL2 ORM
        if: ${{ steps.release.outputs.releases_created }}
        run: npm run build

      - name: 📥 Publishing Package
        if: ${{ steps.release.outputs.releases_created }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
